version: '3'

#networks:
#    fabric_net:
#        external: true

services:
    
    orderer2.dns.com:
        container_name: orderer2.dns.com
        image: trusted-chain/orderer:2.4.6
#        networks:
#            - fabric_net
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7053
#            - ORDERER_GENERAL_GENESISMETHOD=file
#            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
#            - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
#            - ORDERER_KAFKA_VERBOSE=true
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            #           配置无系统通道
            - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
            - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9443
            - ORDERER_ADMIN_TLS_ENABLED=true
            - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
            - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_CHANNELPARTICIPATION_ENABLED=true
              # metrics
#            - ORDERER_OPERATIONS_LISTENADDRESS=orderer2.dns.com:8125
#            - ORDERER_METRICS_PROVIDER=statsd
#            - ORDERER_METRICS_STATSD_ADDRESS=graphite:8125
#            - ORDERER_METRICS_STATSD_NETWORK=udp
#            - ORDERER_METRICS_STATSD_PREFIX=orderer2
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        volumes:
            - /etc/localtime:/etc/localtime
#            - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ./crypto-config/ordererOrganizations/dns.com/orderers/orderer2.dns.com/msp:/var/hyperledger/orderer/msp
            - ./crypto-config/ordererOrganizations/dns.com/orderers/orderer2.dns.com/tls/:/var/hyperledger/orderer/tls
            - ./hyperledger/orderer2:/var/hyperledger/production
        ports:
            - 7053:7053

    