name: CI/CD
# 触发条件为 push
on:
  push:
    branches:
      - main
# 任务
jobs:
  docker: # 描述词, 无实际意义
    runs-on: ubuntu-latest # 运行的环境
    # 步骤
    steps:
      - uses: actions/checkout@v2 # 相当于执行git pull操作，以获取最新的代码
      
      - name: 配置依赖 # 描述词, 无实际意义
        uses: actions/setup-node@v1 # 相当于依赖管理工具
        with: # 配置actions/setup-node@v1的一些属性
          node-version: 18
          
      - name: 打包镜像, 上传 Docker Hub # 描述词, 无实际意义
        run: | # 当前服务器依次执行下面的命令
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          docker build -t luode0320/blog:latest .
          docker push luode0320/blog:latest
