# 此文件相当简单
# 1. 检测到main分支有提交触发jobs任务
# 2. 指定一个github服务器的环境ubuntu-latest
# 3. 执行pull当前的代码到github服务器
# 4. 直接登录docker, 并制作镜像(所有安装依赖等都写在dockerfile中, 不在此执行)
# 5. 连接远程服务器, 停止/删除容器, 重新拉取最新镜像, 启动

name: CI/CD
on:
  workflow_dispatch:
    inputs:
      name:
        description: '手动执行'
        required: true
        default: 'World'
#  push:
#    branches:
#      - main # 触发条件为 push main分支
# 任务
jobs:
  deploy-to-server:
    name: 拉取代码至服务器并构建Docker镜像
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 通过SSH传输代码至服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 10022
          source: '.' # 当前工作目录下的所有文件
          target: '/usr/local/src/code/blog/' # 服务器上的目标目录

      - name: 在服务器上执行Docker构建
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 10022
          script: |
            # 转换到存放代码的目录
            cd /usr/local/src/code/blog
            # 执行Docker构建
            docker build -t luode0320/blog:latest .

            # 容器管理操作，根据需要可调整或移除这部分
            docker rm -f blog
            docker rmi luode0320/blog:latest
            docker pull luode0320/blog:latest
            docker run  -d \
            --restart=always \
            --name blog \
            -p 4000:4000 \
            -v /usr/local/src/blog/data:/app/data \
            luode0320/blog:latest